<?php

declare(strict_types=1);

namespace Anik\Laravel\Centrifugo\Versions\V4;

use Anik\Centrifugo\Methods\V4\Broadcast;
use Anik\Centrifugo\Methods\V4\Publish;
use Anik\Centrifugo\Server\V4;
use Anik\Laravel\Centrifugo\Versions\V3\Centrifugo as CentrifugoV3;

class Centrifugo extends CentrifugoV3
{
    protected function authorizationResolver(): string
    {
        return V4::class;
    }

    protected function getPublishClass(): string
    {
        return Publish::class; // TODO: Change the autogenerated stub
    }

    protected function getBroadcastClass(): string
    {
        return Broadcast::class;
    }
}
